server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://patient-service:8081
          predicates:
            - Path=/patients/**
        - id: note-service
          uri: http://note-service:8082
          predicates:
            - Path=/notes/**, /notes/patient/**
        - id: assessment-service
          uri: http://assessment-service:8083
          predicates:
            - Path=/assessments, /assessments/**

# Sécurité basique pour test
spring.security.user.name: admin
spring.security.user.password: admin123
